# Generated by Django 4.2.5 on 2023-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='about',
            field=models.TextField(default=1, verbose_name='Notebook text'),
            preserve_default=False,
        ),
    ]
